Create auction service with Mongo
amerkul/auction-service pull request #1
Opened 2023-03-24 13:59 UTC by amerkul

2023-03-27 13:57 UTC, h1alexbel requested changes

2023-03-27 13:57 UTC, h1alexbel commented on src/main/resources/application.yml
> +      host: mongodb
host is hardcoded

2023-03-27 14:16 UTC, amerkul commented on src/main/resources/application.yml
> +      host: mongodb
I know It is annoying you))))))

2023-03-28 13:17 UTC, h1alexbel approved these changes

2023-03-28 13:17 UTC, merged